version: '3.8'

services:
  db:
    image: postgres:15
    container_name: dropbox_postgres
    restart: always
    environment:
      POSTGRES_DB: dropboxdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - dropbox_net

  app:
    build: .
    container_name: dropbox_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dropboxdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: pass
    volumes:
      - uploads:/app/uploads
    networks:
      - dropbox_net

volumes:
  pg_data:
  uploads:

networks:
  dropbox_net:
